### ISSUE TITLE
Font-size goes crazy on particular browser window size

### ISSUE THREAD

**Issue by rafalkrupinski** [darktable-org/dtorg#58]
Hi,

when I was browsing the user manual with window width around 1250px, the font started alternating back and forth between smaller and bigger (Safari 12.1.1).

I can upload a screencast if needed.

**Comment by patdavid** [comment]
I think I've seen this before and it's usually related to being a width very close to a media breakpoint.  I don't have a safari handy to test this (iirc, this only happens on Safari _on macOS_ - can someone with macOS test this for me?

**Comment by chellman** [comment]
I just experienced this as well, and it is wacky!  Here's a screencast showing first the effect, then the web inspector with the selected element and section of the CSS rules that's losing its mind highlighted.

http://www.shooflydesign.org/f/DarkTableSafariFreakout.mp4

It seems to happen between ~1145px and ~1226px, roughly (I'm eyeballing it using the web inspector rulers).  None of the media queries I see in the CSS files should be triggering anything at those widths.

**Comment by curiousercreative** [comment]
I just experienced this as well and I've created a pull request to resolve this issue: https://github.com/darktable-org/dtorg/pull/61

**Comment by patdavid** [comment]
Merged, thank you @curiousercreative for the PR.

Not sure why Safari has trouble rendering those breakpoints in particular (this is the second time I've run into this).

**Comment by curiousercreative** [comment]
@patdavid I believe that glitch is a result of the the breakpoint value changing after we've updated the font-size for `html`, which is what `rem` refers to (see code block below for those calculations). Now if you happen to have a viewport width between 640 and 716 or between 1024 and 1228, you'll be bouncing between matching the media query and not matching the media query and because the breakpoint length (as a result of `rem` changing) changes based on this match, you can end up in an infinite loop. So really, it seems that it should be a problem for any browser, but perhaps others have safeguarded against such a scenario?

```css
/* calculations assume default font-size for browser is set to 16px (most common) */
@media (min-width: 40rem) { /* 40 x 16px = 640px */
  html { font-size: 112%; } /* 40 x (16 x 1.12)px = 716.8px */
}
@media (min-width: 64rem) { /* 64 x 16px = 1024px */
  html { font-size: 120%; } /* 64 x *(16 x 1.2)px = 1228.8px */
}
```
